language: node_js

node_js:
  - 'v14.5.0'

jobs:
  include:
    - stage: "Deploy"
      name: "Deploy to QA"
      if: fork = false AND branch = master AND (type = push OR type = api)
      skip_cleanup: true
      env:
        - TF_VAR_stage=prod
      script:
        - ./scripts/deploy.sh
env:
  global:
    - AWS_DEFAULT_REGION=eu-central-1
